-- DEMO-mode seed data only. Never run against a PRODUCTION database.
-- Test user PIN is '1234' (argon2id hash below is a placeholder — replace
-- with a real hash generated by the identity module before using).

INSERT INTO jurisdiction_config (jurisdiction_code, currency_code, minimum_age, kyc_required, regulatory_mode)
VALUES ('PG', 'PGK', 18, false, 'DEMO');

INSERT INTO payment_providers (code, name, is_approved, config)
VALUES ('sandbox', 'Sandbox Payment Provider', true, '{"mode":"simulated"}');

INSERT INTO users (id, mobile_number, pin_hash, status, role)
VALUES ('00000000-0000-0000-0000-000000000001', '+67570000000', '$argon2id$REPLACE_ME', 'ACTIVE', 'CUSTOMER');

INSERT INTO user_profiles (user_id, first_name, last_name, date_of_birth)
VALUES ('00000000-0000-0000-0000-000000000001', 'Demo', 'User', '1995-01-01');

INSERT INTO wallets (id, user_id, currency_code, cached_balance)
VALUES ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'PGK', 0);

INSERT INTO sports (id, name, slug) VALUES
  ('00000000-0000-0000-0000-000000000010', 'Football', 'football');

INSERT INTO leagues (id, sport_id, name, country) VALUES
  ('00000000-0000-0000-0000-000000000011', '00000000-0000-0000-0000-000000000010', 'Premier League', 'England');

INSERT INTO teams (id, name, sport_id) VALUES
  ('00000000-0000-0000-0000-000000000012', 'Arsenal', '00000000-0000-0000-0000-000000000010'),
  ('00000000-0000-0000-0000-000000000013', 'Manchester United', '00000000-0000-0000-0000-000000000010');

INSERT INTO events (id, league_id, home_team_id, away_team_id, start_time, status) VALUES
  ('00000000-0000-0000-0000-000000000014', '00000000-0000-0000-0000-000000000011',
   '00000000-0000-0000-0000-000000000012', '00000000-0000-0000-0000-000000000013',
   now() + interval '2 days', 'SCHEDULED');

INSERT INTO markets (id, event_id, market_type, status) VALUES
  ('00000000-0000-0000-0000-000000000015', '00000000-0000-0000-0000-000000000014', '1X2', 'OPEN');

INSERT INTO selections (id, market_id, name, result) VALUES
  ('00000000-0000-0000-0000-000000000016', '00000000-0000-0000-0000-000000000015', 'Arsenal', 'PENDING'),
  ('00000000-0000-0000-0000-000000000017', '00000000-0000-0000-0000-000000000015', 'Draw', 'PENDING'),
  ('00000000-0000-0000-0000-000000000018', '00000000-0000-0000-0000-000000000015', 'Manchester United', 'PENDING');

INSERT INTO odds (selection_id, decimal_odds) VALUES
  ('00000000-0000-0000-0000-000000000016', 1.85),
  ('00000000-0000-0000-0000-000000000017', 3.40),
  ('00000000-0000-0000-0000-000000000018', 2.10);
